server:
  port: 8081

app:
  jwtSecret: georgeSecretKey
  jwtExpirationMs: 86400000

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true


spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: timesheet
          uri: lb://timesheet
          predicates:
            - Path=/timesheet/**
