spring:
  application:
    name: timesheet
  data:
    mongodb:
      uri: mongodb+srv://test:123@atlascluster.gze84.mongodb.net/mydb?retryWrites=true&w=majority

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}